package tech.dagimtesfaye.cbe_balance_tracker.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF67548E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFEADDFF)
val onPrimaryContainerLight = Color(0xFF220F46)
val secondaryLight = Color(0xFF136682)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBEE9FF)
val onSecondaryContainerLight = Color(0xFF001F2A)
val tertiaryLight = Color(0xFF136682)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBEE9FF)
val onTertiaryContainerLight = Color(0xFF001F2A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFEF7FF)
val onBackgroundLight = Color(0xFF1D1B20)
val surfaceLight = Color(0xFFF5FAFB)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFDCE4E9)
val onSurfaceVariantLight = Color(0xFF40484C)
val outlineLight = Color(0xFF70787D)
val outlineVariantLight = Color(0xFFC0C8CD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFFD2BCFD)

val primaryDark = Color(0xFFD2BCFD)
val onPrimaryDark = Color(0xFF38265C)
val primaryContainerDark = Color(0xFF4F3D74)
val onPrimaryContainerDark = Color(0xFFEADDFF)
val secondaryDark = Color(0xFF8CCFF0)
val onSecondaryDark = Color(0xFF003546)
val secondaryContainerDark = Color(0xFF004D65)
val onSecondaryContainerDark = Color(0xFFBEE9FF)
val tertiaryDark = Color(0xFF8CCFF0)
val onTertiaryDark = Color(0xFF003546)
val tertiaryContainerDark = Color(0xFF004D65)
val onTertiaryContainerDark = Color(0xFFBEE9FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF151218)
val onBackgroundDark = Color(0xFFE7E0E8)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDEE3E5)
val surfaceVariantDark = Color(0xFF40484C)
val onSurfaceVariantDark = Color(0xFFC0C8CD)
val outlineDark = Color(0xFF8A9297)
val outlineVariantDark = Color(0xFF40484C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2B3133)
val inversePrimaryDark = Color(0xFF67548E)







